
name: Terraform CI
on:
  pull_request:
    branches:
      - main
      - develop-branch
    types:
      - opened
      - synchronize
    paths:
      - 'terraform/**'

env:
  TF_VERSION: 1.9.2
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_REGION: ap-northeast-1
  ASSUME_ROLE: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.ACTIONS_ROLE }}
jobs:
  terraform:
    name: terraform
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        workdir: [./terraform, ./terraform/modules/ecr]
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.ASSUME_ROLE }}
        aws-region: ${{ env.AWS_REGION }}
    - name: terraform setup
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ matrix.TF_VERSION }}
    - name: Terraform init
      working-directory: ${{ matrix.workdir }}
      run: terraform init -backend-config="bucket=tmp-hands-on-tf-state-${{ env.AWS_ACCOUNT_ID }}"
    - name: Terraform fmt
      working-directory: ${{ matrix.workdir }}
      run: terraform fmt
    - name: Terraform plan
      working-directory: ${{ matrix.workdir }}
      run: terraform plan -no-color
